pipeline {
  agent none
  stages {
     stage("build")
        {
          agent {
            docker { image 'maven:latest'}
                }
           steps {
             dir("demo"){
                  sh 'mvn -v'
                  echo 'building the application'
                  sh 'mvn -B -DskipTests clean package'
                  stash includes: 'target/*.jar',name:'targetfiles'
             }}
        }
     stage("Test")
        {
          agent {
            docker { image 'maven:latest'}
                }
           steps {
               dir("demo"){
                  echo 'Testing application'
                  sh 'mvn test'
               }}
          post{
            always{junit 'target/surefire-reports/*.xml'}
          }
        }
        }
}
