pipeline {
  agent none
  stages {
     stage("build")
        {
          agent {
            docker { image 'maven:latest'}
                }
           steps {
                  sh 'mvn -v'
                  echo 'building the application'
                }
        }
     stage("deploy")
        {
           steps {
                  echo 'deploying the application'
                }
        }
        }
}
