pipeline {
  agent none
  stages {
    stage('Initialize'){
        def dockerHome = tool 'myDocker'
        env.PATH = "${dockerHome}/bin:${env.PATH}"
    }
     stage("build")
        {
          agent {
            docker { image 'maven:latest'}
                }
           steps {
                  echo 'building the application'
                }
        }
     stage("deploy")
        {
           steps {
                  echo 'deploying the application'
                }
        }
        }
}
